<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.0.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Sign Up Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U7649' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'First Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'First Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Last Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Last Name\' is required.',
				'format' => 'Field \'Last Name\' has an invalid email.'
			)
		),
		'custom_U7631' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.'
			)
		),
		'custom_U7623' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Complete Address',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Complete Address\' is required.'
			)
		),
		'custom_U7659' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Contact Number',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Contact Number\' is required.'
			)
		),
		'custom_U7635' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Birth Date',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Birth Date\' is required.'
			)
		),
		'custom_U7627' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Password',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Password\' is required.'
			)
		),
		'custom_U7645' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Confirm Password',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Confirm Password\' is required.'
			)
		)
	)
);

process_form($form);
?>
